use movies

SELECT ADDRESS
FROM studio
WHERE NAME LIKE 'Disney'

SELECT BIRTHDATE
FROM MOVIESTAR
WHERE NAME LIKE 'Jack Nicholson'

SELECT STARNAME
FROM STARSIN
WHERE MOVIEYEAR = 1980 OR MOVIETITLE = '%Knight%'

SELECT NAME
FROM MOVIEEXEC
WHERE NETWORTH > 10000000

SELECT NAME
FROM MOVIESTAR
WHERE GENDER = 'M' OR ADDRESS = 'Perfect Rd.'
