use ships

SELECT DISTINCT COUNTRY
FROM CLASSES
WHERE NUMGUNS >=ALL (SELECT NUMGUNS
					 FROM CLASSES)

SELECT DISTINCT CLASS
FROM SHIPS --JOIN OUTCOMES ON SHIPS.NAME = OUTCOMES.SHIP
WHERE EXISTS (SELECT SHIP
			  FROM OUTCOMES
			  WHERE RESULT = 'sunk' AND ships.NAME = outcomes.SHIP)

SELECT NAME, CLASS
FROM SHIPS
WHERE EXISTS (SELECT CLASS
			  FROM CLASSES
			  WHERE BORE = 16 AND SHIPS.CLASS = CLASSES.CLASS) 

SELECT BATTLES.NAME
FROM BATTLES JOIN OUTCOMES ON BATTLES.NAME = OUTCOMES.BATTLE
WHERE EXISTS (SELECT *
			  FROM CLASSES
			  WHERE CLASS = 'Kongo' AND OUTCOMES.SHIP = C
