use ships

SELECT *
FROM (SHIPS JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS)

(SELECT *
FROM (SHIPS JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS))
UNION
(SELECT *
FROM SHIPS RIGHT JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS
WHERE CLASSES.CLASS IN (SELECT NAME
					    FROM SHIPS))

SELECT COUNTRY, NAME
FROM (SHIPS JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS) LEFT JOIN OUTCOMES ON NAME = SHIP
WHERE BATTLE IS NULL
ORDER BY COUNTRY

SELECT NAME AS 'Ship Name'
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS
WHERE NUMGUNS >= 7 AND LAUNCHED = 1916

SELECT SHIP, NAME, DATE
FROM OUTCOMES JOIN BATTLES ON BATTLE = NAME
WHERE RESULT LIKE 'sunk'
ORDER BY NAME

SELECT NAME, DISPLACEMENT, LAUNCHED
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS
WHERE NAME = SHIPS.CLASS

SELECT CLASSES.CLASS, TYPE, COUNTRY, NUMGUNS, BORE, DISPLACEMENT
FROM SHIPS RIGHT JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS
WHERE LAUNCHED IS NULL

SELECT NAME, DISPLACEMENT, NUMGUNS
FROM (SHIPS JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS) JOIN OUTCOMES ON NAME = SHIP
WHERE BATTLE = 'North Atlantic'
